amqp:
  admin:
    auto-create: ${AMQP_ADMIN_AUTO_CREATE:true}
  host: ${AMQP_RABBIT_HOST:rabbit}
  port: ${AMQP_RABBIT_PORT:5672}
  username: ${AMQP_RABBIT_USERNAME:adm_videos}
  password: ${AMQP_RABBIT_PASSWORD:123456}

keycloak:
  realm: ${KEYCLOAK_REALM:fc3-codeflix}
  host: ${KEYCLOAK_HOST:http://keycloak.internal:8443}

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:sql459037}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL:kafka:3306}


server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

